version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: elearning-postgres
    restart: always
    environment:
      POSTGRES_DB: elearning_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - elearning-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: elearning-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@elearning.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - elearning-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  elearning-network:
    driver: bridge